#logging.level.org.apache.coyote.http11=debug
spring.messages.basename=messages,errors

server.servlet.session.tracking-modes=cookie

# default 값은 1800(30분). 이 값은 60의 배수로 설정해야함(1분 단위로 설정 가능)
server.servlet.session.timeout=60